# .streamlit/secrets.toml

ORACLE_URL = "https://fa-ewci-test-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/faces/FuseWelcome?_afrLoop=43262226801490116&_adf.ctrl-state=13w8n3ohcv_343"
ORACLE_USER = "AINUR.ALMUKAMBETOVA"
ORACLE_PASS = "Pp3errtG!"